name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install optional deps
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl
      - name: Run tests with coverage (stdlib trace)
        run: |
          make coverage
      - name: Enforce coverage >= 100%
        run: |
          python tools/check_coverage_threshold.py --min 100
      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: |
            coverage_report
            assets/coverage.svg
