name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install deps (runtime + dev)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install openpyxl
      - name: Lint (ruff) and format check (black)
        run: |
          if command -v ruff >/dev/null 2>&1; then ruff --version && ruff check .; else echo 'ruff missing'; fi
          if command -v black >/dev/null 2>&1; then black --version && black --check .; else echo 'black missing'; fi
      - name: Run tests with coverage (stdlib trace)
        run: |
          make coverage
      - name: Enforce coverage >= 90%
        run: |
          python tools/check_coverage_threshold.py --min 90
      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: |
            coverage_report
            assets/coverage.svg
